Changing what `number_qubits` means
HQSquantumsimulations/qoqo-quest pull request #171
Opened 2024-03-13 09:12 UTC by dgupta-hqs

2024-03-13 09:16 UTC, kbarkhqs commented on roqoqo-quest/src/interface/pragma_operations.rs
> +
In here, it seems that the contents of the tmp dict (copied from the `bit_registers` was ignored and overwritten. This would then disregard any setting of true/false in the bit_register by `InputBit`. While Divyanshu was able to identify this bug, I wasn't able to say for sure what the effect of the fix should be - should it flip the result `b` if we have set this index to `true`? Or should the code behave as above, where we just keep `true`, set from InputBit and disregard the calculated `b`?

2024-03-13 09:17 UTC, kbarkhqs commented on roqoqo-quest/tests/integration/backend.rs
> +// Test fails due because the action of InputBit is overwritten.
This is the test that caught the InputBit issue

2024-03-13 09:18 UTC, kbarkhqs commented on roqoqo-quest/tests/integration/backend.rs
> +// Test fails due because the action of InputBit is overwritten.
Without the above addition, it didn't return a vector of 10* [false, true], but instead returned 10*[false, false]

2024-03-15 09:11 UTC, kbarkhqs commented on roqoqo-quest/src/interface/mod.rs
> +            println!("{:?}", operation);
Left-over from debugging

2024-03-15 09:11 UTC, kbarkhqs commented on roqoqo-quest/src/interface/pragma_operations.rs
> +
This fix should be removed

2024-03-15 09:12 UTC, kbarkhqs commented on roqoqo-quest/tests/integration/backend.rs
> +// Test fails due because the action of InputBit is overwritten.
This needs documenting

2024-03-15 09:15 UTC, kbarkhqs commented on roqoqo-quest/src/backend.rs
> +            return Err(RoqoqoBackendError::GenericError { msg: format!(" Number of qubits available in the backend is not sufficient. Available qubits = `{}`, while number of qubits defined in the ci
I would suggest adding a new error type to the roqoqo-quest error enum, to better specify it.

2024-03-15 09:19 UTC, kbarkhqs commented on roqoqo-quest/src/interface/preprocessing.rs
> +}
I would suggest expanding the test section with further testing

2024-03-15 09:19 UTC, kbarkhqs requested changes
Some parts need changing still

2024-03-15 11:12 UTC, dgupta-hqs commented on roqoqo-quest/src/backend.rs
> +            return Err(RoqoqoBackendError::GenericError { msg: format!(" Number of qubits available in the backend is not sufficient. Available qubits = `{}`, while number of qubits defined in the ci
You mean to add a new error type in `RoqoqoBackendError`?

2024-03-18 12:02 UTC, kbarkhqs commented on roqoqo-quest/src/interface/preprocessing.rs
> +                    let bits = u64::BITS - (def.length()).leading_zeros();
Could you explain/document this change?

2024-03-18 12:03 UTC, kbarkhqs commented on roqoqo-quest/src/interface/preprocessing.rs
> +        assert_eq!(used, 4);
How come this passes?

2024-03-18 12:06 UTC, kbarkhqs approved these changes

2024-03-18 13:32 UTC, merged